name: python-template # nome del compose in generale
services:
  python-template:
    image: ghcr.io/matt7c2/python-template
    #build: .
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: python-template
    environment:
      ENV_DOCKER: production
      TZ: Europe/Rome # per impostare il containe rcon il foso orario
    ports: # se serve esporre la porta
      - 3000:3000
    env_file:
      - ../.env